### ISSUE TITLE
PersistenceTests, ValidationTests, ExtensionTests

### ISSUE THREAD

**Issue by gavinking** [jakartaredhat/hibernate-data-tck#12]
I attempted to set up these up in a similar way to what `StandaloneEntityTests` does, but that didn't work. We need to figure out how to run these.

**Comment by starksm64** [comment]
All these tests expect a web container, so I'll have to setup a profile that pulls in the wildfly container.

**Comment by starksm64** [comment]
All passing with a fix for the last issue:
https://github.com/jakartaee/data/issues/709
