### ISSUE TITLE
Project setup issues

### ISSUE THREAD

**Issue by KyleAure** [jakartaredhat/hibernate-data-tck#2]
https://github.com/jakartaredhat/hibernate-data-tck/blob/5b27b07ccfdbd30777c7e272b0302f1e6a4807f4/pom.xml#L213

The `groups` element is a logical operation. 
`standalone,persistence` means: Execute all tests tagged with standalone, Execute all tests tagged with persistence.

That is why you are attempting to execute standalone `nosql` tests.

You should switch this to: 
```xml
<groups><![CDATA[standalone & persistence]]></groups>
```

`standalone & persistence` means: Execute all tests tagged with standalone and persistence
CDATA required otherwise maven will complain about `&`

I think that will make this unnecessary:
https://github.com/jakartaredhat/hibernate-data-tck/blob/5b27b07ccfdbd30777c7e272b0302f1e6a4807f4/pom.xml#L156-L157

Also the EmbeddedContainer that doesn't deploy an application will also not be necessary since our standalone tests won't attempt to call `deploy`

**Comment by starksm64** [comment]
Ok, I have updated this and the structure has changed quite a bit. I pulled the annotation processing into a separate module that creates the augmented tck test class jar, and the runner module runs the the tests. We still have some basic issues to work out in terms of getting the tck entities generated.

**Comment by starksm64** [comment]
Now that I have gotten into testing this, I have the maven.surefire.version set to 3.2.5 and the syntax for groups is comma delimited. There is still strange behavior like running web tests when the core profile is set as the jakarta.tck.profile property. I'll create a bug report on this.

**Comment by starksm64** [comment]
Note I finally found the tag expression syntax:
https://junit.org/junit5/docs/current/user-guide/#running-tests-tag-expressions
