### ISSUE TITLE
creating too many EMFs

### ISSUE THREAD

**Issue by gavinking** [jakartaredhat/hibernate-data-tck#6]
Currently, we appear to be recreating the EMF for every repository we instantiate or something like that.

This is a problem, because test data population is tied to the EMF lifecycle.

I'm not sure whose fault this is, the TCK, or this project.

**Comment by starksm64** [comment]
See if the last commits resolves this. The EMF should be coming from an ApplicationScoped producer value.

**Comment by gavinking** [comment]
Yup, I guess that fixed  it.

Merge https://github.com/jakartaredhat/hibernate-data-tck/pull/7, and then we're down to:

     [ERROR] Tests run: 73, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 55.023

**Comment by gavinking** [comment]
Though, I'm a bit confused. I had expected that fixing the scoping issue would also fix `EntityTests.testUpdateQueryWithoutWhereClause()`. I'm surprised it's still failing.

**Comment by gavinking** [comment]
There still seems to be something a bit screwy here.

If I add:


```java
@Query("select count(this)")
long countAll();
```


to `Boxes`, and change the test by adding some calls to `countAll()`:

```java
    public void testUpdateQueryWithoutWhereClause() {
        // Ensure there is no data left over from other tests:
        shared.removeAll();

        TestPropertyUtility.waitForEventualConsistency();

        assertEquals(0L, boxes.countAll(), "should be zero");

        boxes.saveAll(List.of(Box.of("TestUpdateQueryWithoutWhereClause-01", 125, 117, 44),
                              Box.of("TestUpdateQueryWithoutWhereClause-02", 173, 165, 52),
                              Box.of("TestUpdateQueryWithoutWhereClause-03", 229, 221, 60)));

        TestPropertyUtility.waitForEventualConsistency();

        assertEquals(3L, boxes.countAll(), "should be three");

        // increases length by 12, decreases width by 12, and doubles the height
        assertEquals(3L, shared.resizeAll(12, 2), "should have deleted three");

        ...
}
```

Then the test passes:

    [ERROR] Tests run: 73, Failures: 4, Errors: 0

But if I remove the calls to `boxes.countAll()`, the test fails.

**Comment by gavinking** [comment]
Also moving the `resizeAll()` method from `MultipleEntityRepo` to `Boxes` fixes the test failure.

So it's definitely something to do with having multiple repos.

**Comment by gavinking** [comment]
I now strongly suspect that this is because when we have multiple repos, we get a separate `StatelessSession` for each one. And, because we're not using a JTA `DataSource`, and also because there's anyway no JTA transaction in progress, each `StatelessSession` gets its own JDBC `Connection`.

I'm not really sure what to say about that. I guess we need to inject the `StatelessSession` instead of the `EntityManagerFactory` to make this work.

**Comment by gavinking** [comment]
Solved by setting `hibernate.connection.autocommit=true`.
